# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS_PROJECT_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 830)
        Form.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 511, 241))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 310, 161, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 350, 121, 21))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 380, 141, 31))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 430, 131, 31))
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(170, 170, 170);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(50, 480, 141, 31))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 310, 141, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 350, 131, 21))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(280, 380, 151, 31))
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 430, 141, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(280, 480, 151, 31))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(510, 310, 201, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(510, 350, 61, 21))
        self.label_7.setObjectName("label_7")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(510, 380, 91, 31))
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(650, 350, 51, 21))
        self.label_8.setObjectName("label_8")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(650, 380, 91, 31))
        self.plainTextEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 430, 121, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(560, 480, 151, 31))
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(860, 300, 171, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(860, 350, 131, 21))
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(860, 380, 151, 31))
        self.plainTextEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 430, 111, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(860, 480, 151, 31))
        self.textEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_4.setObjectName("textEdit_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">WE HAVE MADE FIVE(5) FUNCTIONS IN THIS PROJECT</span></p><p><span style=\" font-size:10pt; font-weight:600;\"><br/></span></p><p><span style=\" font-size:10pt; font-weight:600;\">1, GET PARENT()</span></p><p><span style=\" font-size:10pt; font-weight:600;\">2, GET NEXT()</span></p><p><span style=\" font-size:10pt; font-weight:600;\">3, SUM OF RANGE()</span></p><p><span style=\" font-size:10pt; font-weight:600;\">4, PREFIX SUM()</span></p><p><span style=\" font-size:10pt; font-weight:600;\">5, UPDATE VALUE()</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#550000;\">GET PARENT()</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">INSERT CHILD</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "GET PARENT"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#550000;\">GET NEXT()</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; color:#181818;\">INSERT POSITION</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "GET NEXT"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#550000;\">SUM OF RANGE()</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#474747;\">START</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">END</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "GET SUM"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#550000;\">PREFIX SUM()</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">INSERT POSITION</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "GET SUM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

